# Generated by Django 3.2.4 on 2021-07-22 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('number', models.IntegerField(max_length=20)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
